### ISSUE TITLE
split or expose shared utils

### ISSUE THREAD

**Issue by jdalton** [caridy/secure-javascript-environment#39]
I noticed in the creation of distortion callbacks that we could use the shared utils to avoid prototype methods of arrays, maps, sets, etc. We could expose this as its own scoped package or promote use of `@caridy/sjs/lib/shared` (seems a bit like reaching for internals that way though).

**Comment by caridy** [comment]
We discussed this offline... and since that file contains more than just utilities, it contains stuff that are only useful for this project (like the internal whitelist of intrinsics), plus it is very small anyways. We feel that it is ok for folks to have a separate pkg, or just copy them into their project where they plan to write distortions... closing this one.
